# Generated by Django 5.0.3 on 2024-04-22 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='Available', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('audit_date', models.DateField(default=None)),
                ('location', models.CharField(default='', max_length=100)),
                ('availability', models.BooleanField(default=False)),
                ('comments', models.CharField(default='', max_length=200)),
                ('onsite_only', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.user')),
            ],
            options={
                'db_table': 'borrowed_item',
            },
        ),
    ]
