# Generated by Django 5.0.3 on 2024-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='device_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
