# Generated by Django 5.0.3 on 2024-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventoryitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='availability',
            field=models.CharField(default='', max_length=100),
        ),
    ]
