# Generated by Django 5.0.3 on 2024-04-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='audit_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='return_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
