# Generated by Django 5.0.3 on 2024-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='availability',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
