# Generated by Django 5.0.3 on 2024-04-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventoryitem_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='availability',
            new_name='status',
        ),
    ]
