# Generated by Django 5.0.3 on 2024-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
