# Generated by Django 5.0.3 on 2024-04-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='device_type',
            new_name='item_type',
        ),
    ]
