# Generated by Django 5.0.3 on 2024-04-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_device_type_inventoryitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='audit_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
