# Generated by Django 5.0.3 on 2024-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem_audit_date_inventoryitem_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='onsite_only',
            field=models.BooleanField(default=False),
        ),
    ]
